baseURL = "https://pbuff07.github.io/"
languageCode = "zh-cn"
title = "嘴强黑客 /pbuff07"
defaultContentLanguage = "zh-cn"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  description = "赛博空间嘴强王者"
  brand = "嘴强黑客 / pbuff07"
  showReadingTime = true
